# embedding this in chataws_fargate.yml
Resources:
  GPTSystemPromptsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'GPTSystemPrompts'
      AttributeDefinitions:
        - AttributeName: 'prompt_name'
          AttributeType: 'S'
        - AttributeName: 'system_prompt'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'prompt_name'
          KeyType: 'HASH'
        - AttributeName: 'system_prompt'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  GPTSystemPromptsTableArn:
    Description: 'ARN of the GPTSystemPrompts table'
    Value: !GetAtt GPTSystemPromptsTable.Arn
