AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for creating Fargate and resources associated with the Wkid Smaaht application

Parameters:
  VpcId:
    Description: The ID of the VPC
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: The ID of the Subnet
    Type: AWS::EC2::Subnet::Id

  EcrRepositoryUri:
    Description: The URI of the ECR repository
    Type: String

  SlackBotSecretArn:
    Description: The ARN of the Slack Bot Secret in Secrets Manager
    Type: String
    
  SlackAppSecretArn:
    Description: The ARN of the Slack App Secret in Secrets Manager
    Type: String

  OpenAIAPISecretArn:
    Description: The ARN of the OpenAI API Secret in Secrets Manager
    Type: String 

Resources:

  GPTSystemPromptsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'GPTSystemPrompts'
      AttributeDefinitions:
        - AttributeName: 'prompt_name'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'prompt_name'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  FargateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the Fargate task
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
        ClusterName: WkidSmaahtCluster  # Add this line with your desired cluster name    

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ECSSecretsManagerTaskExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: DynamoDBAccessPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            Resource: !GetAtt GPTSystemPromptsTable.Arn


  PolicyForSecretsManager:
    Type: AWS::IAM::Policy
    DependsOn: ExecutionRole
    Properties:
      PolicyName: AllowSecretsManagerAccessSlackGPT
      Roles:
        - !Ref ExecutionRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: 
              - !Ref SlackBotSecretArn
              - !Ref SlackAppSecretArn
              - !Ref OpenAIAPISecretArn

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: '512'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: SlackAppContainer
          Image: !Ref EcrRepositoryUri
          Essential: true
          Secrets:
            - ValueFrom: !Ref SlackBotSecretArn
              Name: SLACK_BOT_TOKEN_WKID_SMAAHT
            - ValueFrom: !Ref OpenAIAPISecretArn
              Name: OPENAI_API_KEY_WKID_SMAAHT
            - ValueFrom: !Ref SlackAppSecretArn
              Name: SLACK_APP_TOKEN_WKID_SMAAHT             
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: SlackAppContainer

  FargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 0
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: 
            - !Ref SubnetId
          SecurityGroups: 
            - !GetAtt FargateSecurityGroup.GroupId
      TaskDefinition: !Ref TaskDefinition

  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: /ecs/SlackAppContainer
      RetentionInDays: 7
